name: OrangeFox - Build - Test

on:
  workflow_dispatch:

jobs:
  build:
    name: 🦊 Building OrangeFox Recovery
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v4
              
    - name: OrangeFox Build
      uses: ./
      with:
        USER_NAME: 'Veniamin668'
        USER_EMAIL: 'venik1821@gmail.com'
        DEVICE_TREE: 'https://github.com/Veniamin668/device_redmi_klein'
        DEVICE_TREE_BRANCH: '12.1'
        DEVICE_PATH: 'device/xiaomi/missi'
        DEVICE_NAME: 'klein'
        BUILD_TARGET: 'vendorboot'
        TG_CHAT_ID: '${{ secrets.TG_CHAT_ID }}'
        TG_TOKEN: '${{ secrets.TG_TOKEN }}'
        MAINTAINER_URL: 'https://i.ibb.co.com/8gyjXq06/maintainer.png'
        GH_RELEASE: 'true'
